import { NextRequest, NextResponse } from 'next/server';
import { getDb } from '@/lib/db';
import { getSession } from '@/lib/auth';
import { getFileFromGithub, updateFileInGithub } from '@/lib/github';
import yaml from 'js-yaml';

/**
 * Articles API
 * - 草稿：保存到数据库
 * - 发布：提交到 GitHub
 */

function generateStaticHTML(article: { title: string; authorName: string; content: string; createdAt: string; tags?: string[] }): string {
  const escapeHtml = (str: string) => str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  
  const markdownToHtml = (md: string): string => {
    return md
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/`(.+?)`/g, '<code>$1</code>')
      .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>');
  };

  const tagsHtml = article.tags?.length ? `<div class="tags">${article.tags.map(t => `<span class="tag">${escapeHtml(t)}</span>`).join(' ')}</div>` : '';

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(article.title)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.8; color: #333; background: #f5f5f5; }
    .container { max-width: 800px; margin: 0 auto; padding: 40px 20px; }
    .article { background: #fff; border-radius: 8px; padding: 40px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    h1 { font-size: 2em; margin-bottom: 16px; color: #1a1a1a; }
    .meta { color: #666; margin-bottom: 24px; font-size: 0.9em; }
    .author { font-weight: 500; }
    .tags { margin-top: 16px; }
    .tag { display: inline-block; background: #e8f4fd; color: #1976d2; padding: 4px 12px; border-radius: 16px; font-size: 0.85em; margin-right: 8px; }
    .content { margin-top: 32px; }
    .content h1, .content h2, .content h3 { margin: 24px 0 12px; }
    .content p { margin: 16px 0; }
    .content code { background: #f0f0f0; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }
    .content blockquote { border-left: 4px solid #1976d2; padding-left: 16px; margin: 16px 0; color: #555; }
    .content li { margin-left: 24px; margin-bottom: 8px; }
    .footer { text-align: center; margin-top: 40px; color: #999; font-size: 0.85em; }
  </style>
</head>
<body>
  <div class="container">
    <article class="article">
      <h1>${escapeHtml(article.title)}</h1>
      <div class="meta">
        <span class="author">${escapeHtml(article.authorName)}</span>
        <span> · ${new Date(article.createdAt).toLocaleDateString('zh-CN')}</span>
        ${tagsHtml}
      </div>
      <div class="content">
        <p>${markdownToHtml(escapeHtml(article.content))}</p>
      </div>
    </article>
    <div class="footer">
      <p>Generated by ZhouZBoss</p>
    </div>
  </div>
</body>
</html>`;
}

export async function GET(req: NextRequest) {
  try {
    const db = getDb();
    const index = await db.hgetall('articles:index');
    
    const articles = Object.entries(index).map(([id, data]) => ({
      id,
      ...JSON.parse(data),
    }));

    // 按日期降序排序
    articles.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

    return NextResponse.json(articles);
  } catch (error) {
    console.error(JSON.stringify({ type: 'list_articles_error', message: (error as Error).message }));
    return NextResponse.json({ error: '获取文章列表失败' }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  const session = await getSession();
  if (!session) {
    return NextResponse.json({ error: '未登录' }, { status: 401 });
  }

  try {
    const { title, content, tags, coverImage, status } = await req.json();
    const id = `art-${Date.now().toString(36)}`;
    const now = new Date().toISOString();

    // 获取 GitHub 配置
    const db = getDb();
    const configStr = await db.get('config:main');
    let config: any = {};
    if (configStr) {
      config = JSON.parse(configStr);
    }

    // 如果是发布状态，需要检查 GitHub 配置
    if (status === 'published') {
      if (!config.githubRepo || !config.githubToken) {
        return NextResponse.json({ error: '发布文章需要配置 GitHub，请先在系统配置中设置' }, { status: 400 });
      }
    }

    // 文章元数据（存数据库）
    const articleMeta = {
      id,
      title,
      content: content || '', // 草稿内容存数据库
      authorId: session.uid,
      authorName: session.email.split('@')[0],
      tags: tags || [],
      coverImage: coverImage || '',
      status: status || 'draft',
      createdAt: now,
      updatedAt: now,
      filePath: `articles/${id}.md`,
    };

    // 1. 保存元数据和内容到数据库
    await db.set(`article:data:${id}`, JSON.stringify(articleMeta));
    await db.hset('articles:index', id, JSON.stringify(articleMeta));

    // 2. 如果是发布状态，提交到 GitHub
    if (status === 'published' && config.githubRepo && config.githubToken) {
      const frontMatter = {
        title,
        author: articleMeta.authorName,
        tags: articleMeta.tags,
        cover: coverImage || '',
        date: now,
        status: 'published',
      };
      
      const fileContent = `---\n${yaml.dump(frontMatter)}---\n\n${content}`;
      
      await updateFileInGithub({
        repo: config.githubRepo,
        token: config.githubToken,
        path: `articles/${id}.md`,
        content: fileContent,
        message: `feat: publish article "${title}"`,
      });

      // 生成静态 HTML 页面
      const htmlContent = generateStaticHTML(articleMeta);
      await updateFileInGithub({
        repo: config.githubRepo,
        token: config.githubToken,
        path: `pages/${articleMeta.authorName}/${id}.html`,
        content: htmlContent,
        message: `feat: generate static page for "${title}"`,
      });
    }

    return NextResponse.json({ success: true, id });
  } catch (error) {
    console.error(JSON.stringify({ type: 'create_article_error', message: (error as Error).message }));
    return NextResponse.json({ error: '创建文章失败' }, { status: 500 });
  }
}
