site:
  title: Originium Kernel
  description: 现代内容发布平台
  heroTitleLine1: ''
  heroTitleLine2: ''
  lang: zh-CN
appearance:
  background:
    url: ''
    opacity: 0.8
  customCSS: ''
  customHead: ''
  loading:
    page:
      type: waves
      color: '#c084fc'
      position: center
    navigation:
      type: antd
      color: '#c084fc'
    slogans:
      - 欢迎拜访
      - 歡迎拜訪
      - Welcome, my friend!
      - 訪問へようこそ
      - 嗨，别来无恙
      - 不忘初心，一生浪漫
      - 最近还好吗？
      - 流星，落花，萤火
      - 马车越空，晃荡越响
      - 在这里，时光静好
      - Hello ！
      - 心之所向，愿你常在
      - 每个瞬间，因你而美好
      - 每一次相遇，都是一场浪漫
access:
  posts:
    public:
      - '*'
    private: []
  faces:
    public: []
    private:
      - '*'
  diary:
    public: []
    private:
      - '*'
auth:
  allowRegistration: false
nav:
  enable: true
  travelling: true
  clock: true
  menu:
    - title: 网页
      item:
        - name: 博客
          link: https://amiya.giize.com/
          icon: /img/favicon.ico
    - title: 项目
      item:
        - name: Jyf0214
          link: /Jyf0214
          icon: /Jyf0214
mourn:
  enable: true
  days:
    - 4-5
    - 5-12
    - 7-7
    - 9-18
    - 12-13
highlight:
  theme: light
  copy: true
  lang: true
  shrink: false
  heightLimit: 330
  wordWrap: true
copy:
  enable: true
  copyright:
    enable: false
    limitCount: 50
social:
  Github: https://github.com/Jyf0214
authorStatus:
  enable: false
  statusImg: ''
  skills: []
cover:
  indexEnable: true
  asideEnable: true
  archivesEnable: true
  position: left
  defaultCover:
    - /img/default_cover.jpg
errorImg:
  flink: /img/friend_404.gif
  postPage: /img/404.jpg
postMeta:
  page:
    dateType: created
    dateFormat: simple
    categories: true
    tags: true
    label: false
  post:
    dateType: both
    dateFormat: date
    categories: true
    tags: true
    label: true
    unread: false
wordcount:
  enable: false
  postWordcount: false
  min2read: true
  totalWordcount: false
toc:
  post: true
  page: false
  number: true
  expand: false
  styleSimple: false
copyright:
  enable: true
  decode: false
  authorHref: ''
  location: 中国
  license: CC BY-NC-SA 4.0
  licenseUrl: https://creativecommons.org/licenses/by-nc-sa/4.0/
  avatarSinks: true
  authorImgBack: ''
  authorImgFront: ''
  authorLink: /
reward:
  enable: true
  qrCodes:
    - img: ''
      link: ''
      text: 微信
    - img: ''
      link: ''
      text: 支付宝
postEdit:
  enable: false
  github: false
share:
  sharejs:
    enable: true
    sites: facebook,twitter,wechat,weibo,qq
  addtoany:
    enable: false
    item: facebook,twitter,wechat,sina_weibo,email,copy_link
mainTone:
  enable: false
  mode: api
footer:
  owner:
    enable: true
    since: 2020
  customText: ''
  runtime:
    enable: false
    launchTime: 04/01/2021 00:00:00
_testField: this-should-be-preserved-by-surgical-save-2026
users:
  '169313142':
    avatar: https://avatars.githubusercontent.com/u/169313142?v=4
