import { NextRequest, NextResponse } from 'next/server';
import { getDb } from '@/lib/db';
import { getSession } from '@/lib/auth';
import { getFileFromGithub, updateFileInGithub } from '@/lib/github';
import yaml from 'js-yaml';

/**
 * Article Detail API (GET, PATCH, DELETE)
 * - 草稿：内容从数据库读取
 * - 发布：内容从 GitHub 读取
 */

function generateStaticHTML(article: { title: string; authorName: string; content: string; createdAt: string; tags?: string[] }): string {
  const escapeHtml = (str: string) => str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  
  const markdownToHtml = (md: string): string => {
    return md
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/`(.+?)`/g, '<code>$1</code>')
      .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>');
  };

  const tagsHtml = article.tags?.length ? `<div class="tags">${article.tags.map(t => `<span class="tag">${escapeHtml(t)}</span>`).join(' ')}</div>` : '';

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(article.title)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.8; color: #333; background: #f5f5f5; }
    .container { max-width: 800px; margin: 0 auto; padding: 40px 20px; }
    .article { background: #fff; border-radius: 8px; padding: 40px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    h1 { font-size: 2em; margin-bottom: 16px; color: #1a1a1a; }
    .meta { color: #666; margin-bottom: 24px; font-size: 0.9em; }
    .author { font-weight: 500; }
    .tags { margin-top: 16px; }
    .tag { display: inline-block; background: #e8f4fd; color: #1976d2; padding: 4px 12px; border-radius: 16px; font-size: 0.85em; margin-right: 8px; }
    .content { margin-top: 32px; }
    .content h1, .content h2, .content h3 { margin: 24px 0 12px; }
    .content p { margin: 16px 0; }
    .content code { background: #f0f0f0; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }
    .content blockquote { border-left: 4px solid #1976d2; padding-left: 16px; margin: 16px 0; color: #555; }
    .content li { margin-left: 24px; margin-bottom: 8px; }
    .footer { text-align: center; margin-top: 40px; color: #999; font-size: 0.85em; }
  </style>
</head>
<body>
  <div class="container">
    <article class="article">
      <h1>${escapeHtml(article.title)}</h1>
      <div class="meta">
        <span class="author">${escapeHtml(article.authorName)}</span>
        <span> · ${new Date(article.createdAt).toLocaleDateString('zh-CN')}</span>
        ${tagsHtml}
      </div>
      <div class="content">
        <p>${markdownToHtml(escapeHtml(article.content))}</p>
      </div>
    </article>
    <div class="footer">
      <p>Generated by ZhouZBoss</p>
    </div>
  </div>
</body>
</html>`;
}

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  try {
    const db = getDb();
    const metaStr = await db.get(`article:data:${id}`);
    if (!metaStr) {
      return NextResponse.json({ error: '文章不存在' }, { status: 404 });
    }
    
    const meta = JSON.parse(metaStr);
    let content = meta.content || ''; // 优先从数据库获取内容
    
    // 如果是发布状态且数据库没有内容，尝试从 GitHub 获取
    if (meta.status === 'published' && !content) {
      const configStr = await db.get('config:main');
      if (configStr) {
        const config = JSON.parse(configStr);
        if (config.githubRepo && config.githubToken) {
          const file = await getFileFromGithub(config.githubRepo, config.githubToken, `articles/${id}.md`);
          if (file) {
            const match = file.content.match(/^---\n[\s\S]*?\n---\n\n?([\s\S]*)$/);
            if (match) {
              content = match[1];
            } else {
              content = file.content;
            }
          }
        }
      }
    }

    return NextResponse.json({ ...meta, content });
  } catch (error) {
    console.error(JSON.stringify({ type: 'get_article_error', message: (error as Error).message }));
    return NextResponse.json({ error: '获取文章失败' }, { status: 500 });
  }
}

export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const session = await getSession();
  if (!session) return NextResponse.json({ error: '未登录' }, { status: 401 });

  try {
    const body = await req.json();
    const db = getDb();
    
    const metaStr = await db.get(`article:data:${id}`);
    if (!metaStr) return NextResponse.json({ error: '文章不存在' }, { status: 404 });
    
    const meta = JSON.parse(metaStr);
    
    // 检查权限
    if (meta.authorId !== session.uid && session.role !== 'admin' && session.role !== 'sudo') {
      return NextResponse.json({ error: '无权限' }, { status: 403 });
    }

    // 如果是发布状态，检查 GitHub 配置
    if (body.status === 'published') {
      const configStr = await db.get('config:main');
      let config: any = {};
      if (configStr) {
        config = JSON.parse(configStr);
      }
      if (!config.githubRepo || !config.githubToken) {
        return NextResponse.json({ error: '发布文章需要配置 GitHub' }, { status: 400 });
      }
    }

    const updated = { 
      ...meta, 
      ...body, 
      content: body.content !== undefined ? body.content : meta.content,
      updatedAt: new Date().toISOString() 
    };
    
    // 更新数据库
    await db.set(`article:data:${id}`, JSON.stringify(updated));
    await db.hset('articles:index', id, JSON.stringify(updated));

    // 如果是发布状态，同步到 GitHub
    if (body.status === 'published' || (meta.status === 'published' && body.content)) {
      const configStr = await db.get('config:main');
      if (configStr) {
        const config = JSON.parse(configStr);
        if (config.githubRepo && config.githubToken) {
          const frontMatter = {
            title: updated.title,
            author: updated.authorName,
            tags: updated.tags,
            cover: updated.coverImage || '',
            date: updated.createdAt,
            status: updated.status,
          };
          const fileContent = `---\n${yaml.dump(frontMatter)}---\n\n${updated.content || ''}`;
          
          await updateFileInGithub({
            repo: config.githubRepo,
            token: config.githubToken,
            path: `articles/${id}.md`,
            content: fileContent,
            message: `update: article "${updated.title}"`,
          });

          // 生成静态 HTML 页面
          const htmlContent = generateStaticHTML(updated);
          await updateFileInGithub({
            repo: config.githubRepo,
            token: config.githubToken,
            path: `pages/${updated.authorName}/${id}.html`,
            content: htmlContent,
            message: `update: static page for "${updated.title}"`,
          });
        }
      }
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error(JSON.stringify({ type: 'update_article_error', message: (error as Error).message }));
    return NextResponse.json({ error: '更新文章失败' }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const session = await getSession();
  if (!session) return NextResponse.json({ error: '未登录' }, { status: 401 });

  try {
    const db = getDb();
    const metaStr = await db.get(`article:data:${id}`);
    if (!metaStr) return NextResponse.json({ error: '文章不存在' }, { status: 404 });
    
    const meta = JSON.parse(metaStr);

    // 管理员直接删除
    if (session.role === 'admin' || session.role === 'sudo') {
      // 删除数据库元数据
      await db.del(`article:data:${id}`);
      await db.hdel('articles:index', id);
      
      // 删除 GitHub 文件
      const configStr = await db.get('config:main');
      if (configStr) {
        const config = JSON.parse(configStr);
        if (config.githubRepo && config.githubToken) {
          const { deleteFileFromGithub } = await import('@/lib/github');
          await deleteFileFromGithub(config.githubRepo, config.githubToken, `articles/${id}.md`);
          // 删除静态页面
          await deleteFileFromGithub(config.githubRepo, config.githubToken, `pages/${meta.authorName}/${id}.html`);
        }
      }
      
      return NextResponse.json({ success: true, message: '已永久删除' });
    }

    // 普通用户：进入删除队列（30天缓冲）
    if (meta.authorId !== session.uid) {
      return NextResponse.json({ error: '无权限' }, { status: 403 });
    }

    const deletionInfo = {
      ...meta,
      status: 'pending_deletion',
      deletionRequestedAt: new Date().toISOString(),
    };

    await db.set(`article:data:${id}`, JSON.stringify(deletionInfo));
    await db.hdel('articles:index', id);
    await db.hset('articles:index', id, JSON.stringify(deletionInfo));

    return NextResponse.json({ 
      success: true, 
      message: '已提交删除申请，30天后自动删除' 
    });
  } catch (error) {
    console.error(JSON.stringify({ type: 'delete_article_error', message: (error as Error).message }));
    return NextResponse.json({ error: '删除文章失败' }, { status: 500 });
  }
}
